#==============================
# General site config
#==============================

name: "Imaginary Design"
description: Designer
url: http://imaginarydesign.co.uk

markdown: redcarpet
highlighter: pygments # or rouge or null
permalink: /articles/:title/

#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]
exclude: ["node_modules", "bower_components" , "gulpfile.js", "bower.json" , "package.json", "src"]
