#==============================
# General site config
#==============================

name: "Imaginary Design"
description: Designer
url: http://imaginarydesign.co.uk

markdown: redcarpet
highlighter: null # or rouge or null
permalink: /writing/:title/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections: 
  resources:
    output: true
    permalink: /:collection/:title/
  reading:
    output: true
    permalink: /:collection/:title/

#==============================
# File inclusions/exclusions
#==============================

include: [".htaccess"]
exclude: ["node_modules", "bower_components" , "gulpfile.js", "bower.json" , "package.json", "src"]
